### ISSUE TITLE
Animate various doors in levels after the tutorial.

### ISSUE THREAD

**Issue by DustyGreen64** [CS3398-Cobalt-Salutations/EpicGorillaSphere#170]
So here's my idea on this what if we made all our hazards none sphere objects...mostly like cubes. Cause they are the enemy. So this task Mitchell if you choose to accept it is to animate something like a thwomp block and make a rolling cube that could be either a chase obstacle (think the Orca from Sonic Adventure 1...or the Truck from Sonic Adventure 2...You have to run from things in Sonic a lot....OH the boulder in Indiana Jones...but a Cube boulder.) or a frogger type obstacle that crosses your path and you need to time getting past it.

**Comment by mjl71** [comment]
Changing this to animating doors in other levels, as we didn't end up adding any hazards.
